version: "3"
services:
  app:
    build: .
    ports:
      - 5500:5500
    env_file:
      - .env
    # environment:
    #   - DATABASE_URL="postgresql://postgres:Ksv1404@@localhost:5432/apptodo"
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ksv1404@
      - POSTGRES_DB=apptodo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-data:
